name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository and all submodules
      uses: actions/checkout@v2
      with:
        submodules: "recursive"
        
    - name: Provide MSVC to action
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache Build
      id: cache-build
      uses: actions/cache@v2
      with:
        path: out/build
        key: ${{ runner.os }}-build

    - name: Run CMake
      id: run-cmake
      env:
        CC: cl.exe
        CXX: cl.exe
      uses: lukka/run-cmake@v2.5
      with:
        buildDirectory: ${{ github.workspace }}/out/build/x64-Debug/
        cmakeListsOrSettingsJson: "CMakeSettingsJson"
        configurationRegexFilter: "^x64\\-Debug$"

